# Generated by Django 5.1.5 on 2025-01-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rv60app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doct_exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctrina', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(blank=True, null=True)),
                ('desde', models.CharField(blank=True, null=True)),
                ('hasta', models.CharField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('foto', models.CharField(blank=True, null=True)),
                ('id_fk_timeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rv60app.timeline')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, null=True)),
                ('id_fk_doct_exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rv60app.doct_exp')),
                ('id_fk_expositor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rv60app.expositor')),
            ],
        ),
    ]
