# Generated by Django 5.1.5 on 2025-01-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rv60app', '0002_doct_exp_expositor_timeline_urls_tdetail_video'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autor',
            table='autor',
        ),
    ]
