# Generated by Django 5.1.5 on 2025-01-24 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rv60app', '0003_alter_autor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='capitulo',
            table='capitulo',
        ),
        migrations.AlterModelTable(
            name='diccionario',
            table='diccionario',
        ),
        migrations.AlterModelTable(
            name='division',
            table='division',
        ),
        migrations.AlterModelTable(
            name='doct_exp',
            table='doct_exp',
        ),
        migrations.AlterModelTable(
            name='doct_verso',
            table='doct_verso',
        ),
        migrations.AlterModelTable(
            name='doctrina',
            table='doctrina',
        ),
        migrations.AlterModelTable(
            name='expositor',
            table='expositor',
        ),
        migrations.AlterModelTable(
            name='lectura',
            table='lectura',
        ),
        migrations.AlterModelTable(
            name='libro',
            table='libro',
        ),
        migrations.AlterModelTable(
            name='tdetail',
            table='tdetail',
        ),
        migrations.AlterModelTable(
            name='tema',
            table='tema',
        ),
        migrations.AlterModelTable(
            name='timeline',
            table='timeline',
        ),
        migrations.AlterModelTable(
            name='urls',
            table='urls',
        ),
        migrations.AlterModelTable(
            name='versiculo',
            table='versiculo',
        ),
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
    ]
