# Generated by Django 5.1.5 on 2025-01-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rv60app', '0004_alter_capitulo_table_alter_diccionario_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doct_texto',
            table='doct_texto',
        ),
    ]
